#Workflow
name: Deploy To S3 And Invalidate Cloudfront

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
        #marketplace에서 확인

      - name: Install dependencies
        run: npm install

      - name: building
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete S3 files
        run: aws s3 rm --recursive s3://facebook-web-page-001

      - name: Upload repository files to S3
        run: aws s3 cp ./dist s3://facebook-web-page-001/ --recursive

      - name: Cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E3R9V7EWHX654R --paths "/*"
